### ISSUE TITLE
Associate ssh:// URLs with FluentTerminal

### ISSUE THREAD

**Issue by mjs** [jumptrading/FluentTerminal#1]
Have a way, preferably done as part of installation, to set up url handlers for ssh:// that feed through to Fluent such that it opens a new shell in a new tab and ssh's to the host and optional user specified.

More here: https://msdn.microsoft.com/en-us/windows/desktop/aa767914

**Comment by peske** [comment]
Implemented opening in a new tab, as demonstrated in https://www.youtube.com/watch?v=s3ppVJspV50. We'll need to handle what will happen if we have several FluentTerminal windows opened though...
