### ISSUE TITLE
Copy on select regression in 1.1.66 vs 1.1.60

### ISSUE THREAD

**Issue by daviesalex** [jumptrading/FluentTerminal#108]
Confirmed for 2 users. 

Copy on select works in 1.1.60. Upgrade to 1.1.66 and copy on select does not work (and often seems to crash the terminal). This also occurred on a new install. 

The change was the merge upstream (with upgraded xterm.js) PR.

**Comment by MaxRis** [comment]
Can repro the issue on latest upstream as well. Will take a look into it.
