### ISSUE TITLE
Handling ssh.exe location / absence

### ISSUE THREAD

**Issue by peske** [jumptrading/FluentTerminal#11]
Currently we're hardcoding OpenSSH location: `C:\Windows\System32\OpenSSH\ssh.exe`. But we should be more careful with that:

1. Not use `C:\Windows`, but defined placeholders;
2. Check if it is present, and do something if it isn't (like installing SSH client Windows feature);
3. Check how it behaves in both 32 and 64 bit Windows (I believe that @nikitar020 has reported some WOW64 issues).

**Comment by nikitar020** [comment]
point 1 is fixed by PR https://github.com/jumptrading/FluentTerminal/pull/28

**Comment by nikitar020** [comment]
A PR for fixing this has been created in the upstream repo: https://github.com/felixse/FluentTerminal/pull/316

**Comment by MaxRis** [comment]
Should be resolved by above mentioned Nikita's PR.
