### ISSUE TITLE
Keybindings for local and SSH profiles should honour "Open new terminals as windows" setting

### ISSUE THREAD

**Issue by enigmeow** [jumptrading/FluentTerminal#113]
If "Open new terminals as Windows" is set, the "new remote tab" should be "new remote window" and it should actually spawn a window instead of creating a new tab.

**Comment by mjs** [comment]
To clarify, are you suggesting that the "New SSH Tab" key bindings should create a new window if "Open new terminals as Windows" is set. If so, did you know there are already separate keybindings for creating new SSH sessions in windows (both adhoc and using SSH profiles?).

Or are you asking for keybindings for SSH profiles to result in windows being opened if "Open new terminals as Windows" is set? (as also discussed on https://github.com/jumptrading/FluentTerminal/issues/115). This certainly seems sensible to me.

**Comment by enigmeow** [comment]
as far as I can tell, there is no way for me to make a single key binding that opens the default ssh profile as a new window.  I can make one that opens a new window but it defaults to the non-ssh default profile.  I can also make a keyboard sequence that will add a ssh tab using my default profile.  Just no way to do it both at the same time.

My habit is now to open the new window, open the default ssh profile, select the previous tab, and close it...      So,  the second option,.  If "open new terminal as windows" is set, and I hit the key binding to open the default ssh profile, I would love it to pop up as a new window.  thank you

**Comment by mjs** [comment]
Cool, that's sensible. Thanks for clarifying.

**Comment by peske** [comment]
'Default SSH profile' feature at the moment isn't fully compliant with 'Default profile' in regular, _non-remote_ profiles. At the moment I'm reworking it so that, if you select 'Set Default' on a remote profile, the next time when you open the app, it'll open this profile. Basically the same behavior as with regular profiles. Makes sense?

**Comment by mjs** [comment]
@enigmeow as far as I'm aware there isn't a keybinding for directly opening the default SSH profile. Can you clarify what you're using here?

The SSH keybindings that exist are:
- New SSH tab (adhoc SSH connection)
- New SSH window (adhoc SSH connection)
- New SSH profile tab (selecting from a list of configured SSH profiles)
- New SSH profile window (selecting from a list of configured SSH profiles)

Note that https://github.com/felixse/FluentTerminal/pull/399 rationalises the default SSH keybindings somewhat.

**Comment by mjs** [comment]
I think this is now solved by recent changes. Please re-open if there's still more to do here.
