### ISSUE TITLE
for ssh connections, let me turn mosh on by default

### ISSUE THREAD

**Issue by enigmeow** [jumptrading/FluentTerminal#114]

**Comment by MaxRis** [comment]
@enigmeow @mjs @peske 
What if to have separate Settings page, for example, `SSH Settings` next to `SSH Profiles`, and to configure from there "mosh by default", line endings, ConPTY usage, theme and everything else customizable for SSH connections? Configured defaults will be automatically applied to "New SSH profile" and "SSH info" (CTRL+SHIFT+Y) dialogs. Could you please advice with ideas

**Comment by enigmeow** [comment]
Sure!  That would work great!

**Comment by mjs** [comment]
@MaxRis I hink a separate layer of defaults just for SSH connections could be confusing and adds unnecessary complexity. I believe @felixse also leans this way (although it would be good to confirm).

How about just having "Default to Mosh for SSH connections" option at the bottom of the General settings page? That would solve the problem.

As you said, this should be used as the default for the "Use Mosh" checkbox for both ad hoc SSH connections and new SSH profiles.

**Comment by MaxRis** [comment]
New Settings option (turned on by default) is available in latest build v1.1.201.0 https://github.com/jumptrading/FluentTerminal/releases/download/1.1.201.0/FluentTerminalInstaller-v1.1.201.0-52a864b.msi
