### ISSUE TITLE
No way to assign a keybinding for new ssh windows

### ISSUE THREAD

**Issue by enigmeow** [jumptrading/FluentTerminal#115]

**Comment by MaxRis** [comment]
Have you tried latest 1.1.179.0 available build and missing mentioned feature there?
Most recent build https://github.com/jumptrading/FluentTerminal/releases/tag/1.1.179.0 contains new added `SSH Profiles` feature to create and reuse ssh/mosh profiles in similar way how usual `Profiles` work. Keybinding assigning is also a part of new added functionality.
![2019-06-09_16-23-27-SSH-Profiles-Keybindigs](https://user-images.githubusercontent.com/1928902/59159560-1619cc00-8ad4-11e9-9556-0ac660304098.png)

**Comment by enigmeow** [comment]
This creates a new tab despite me having "Open new terminals as Windows" set.  Otherwise, it would be perfect.  Thank you

**Comment by mjs** [comment]
Closing this as it is covered by #113
