### ISSUE TITLE
middle mouse button paste please

### ISSUE THREAD

**Issue by cjw296** [jumptrading/FluentTerminal#118]
Really missing this now...

**Comment by MaxRis** [comment]
That should be already supported, could you please take a look at Settings/Mouse to turn it on

![2019-06-09_16-15-23-middle-mouse-support-in-settings](https://user-images.githubusercontent.com/1928902/59159426-24ff7f00-8ad2-11e9-90c2-4fb4efd7516a.png)

**Comment by cjw296** [comment]
Perfect, thanks!
