### ISSUE TITLE
Remote tab desktop shortcut "Invalid Link" bug

### ISSUE THREAD

**Issue by mass** [jumptrading/FluentTerminal#119]
In the "New Remote Tab" dialog, there is an option to "Save Shortcut" so that you can open that remote tab from a desktop shortcut. This used to work for me a few releases ago, I don't remember exactly which.

Now, when I click a saved shortcut, I get this error: `Invalid Link: Object reference not set to an instance of an object.` and the program exits.

Here is the shortcut "URL": `mosh://amass@rpoil-aml1?mosh_ports=60001-60999`

**Comment by peske** [comment]
This bug is solved in https://github.com/felixse/FluentTerminal/pull/403. Just waiting for @felixse to merge.

**Comment by peske** [comment]
Solved.
