### ISSUE TITLE
ConPTY & 256-colors introduces significant lag/unresponsiveness

### ISSUE THREAD

**Issue by mass** [jumptrading/FluentTerminal#120]
When I enable the ConPTY option, my terminal windows become very laggy to type in & navigate. I notice this with and without tmux. When testing the same ssh setup without ConPTY, typing is very responsive.

Without using ConPTY, I believe WinPTY is used, and this does not support the full 256 color space.  So I have to choose between limited color support and pretty bad typing responsiveness.

**Comment by mjs** [comment]
Interesting - I haven't noticed this before. Does the terminal start out responsive and then get slower or is it slow for you from the start? Does this apply to both local and SSH connections?

**Comment by enigmeow** [comment]
i noticed this effect as well.  Just scrolling through a large file is very laggy when using ConPty

**Comment by daviesalex** [comment]
Before we do anything here its worth checking if this magically goes away with 1903. They did a lot of ConPty improvements in that release (that release wont come to Jump folk for another few months, though).

**Comment by MaxRis** [comment]
@enigmeow can't repro scrolling performance issue with ConPty/SSH. I'm trying with `vim` over large text file by holding CTRL+D. Curious what size of terminal window you have and how long the lines of text in the file you are scrolling. Performance issue to appear might depends on some conditions.

**Comment by MaxRis** [comment]
what if the issue is less observable on "top" hardware

**Comment by daviesalex** [comment]
I pinged the original reporter on Slack to see if I can reproduce this. I have identical hardware to him; its "top".

**Comment by mass** [comment]
Sorry for the delay on this. Steps to reproduce:

0) Open a fresh terminal session. I am using a "Remote tab", but I'm not sure if the issue is only noticeable through SSH. Note: you do not need to open TMUX. The behavior happens inside and outside of TMUX.

1) Set your ~/.vimrc to display a 256-palette color, like this:
 `hi Normal ctermfg=178 ctermbg=233 cterm=NONE`

2) Make sure your terminal is configured to use 256-colors:
`export TERM=xterm-256color`

3) Open up a large text file in vim. Navigate around the file. You should see significant lag.

4) Now turn off 256-colors:
`export TERM=xterm`

5) Open up the large text file again. There should be minimal lag/unresponsiveness now.

Something about ConPTY seems to not be playing nicely with 256-color support. This is a low-priority issue.

**Comment by daviesalex** [comment]
Pretty sure the status here is that this was reproduced with other terminals, and is a Windows/ConPTY bug. The next step here is probably to test this with the latest version of Windows... but in practice this is a perfectly acceptable workaround:

```
[adavies@ljoit-adl1 ~]$ grep TERM .bashrc
export TERM=xterm 
```
