### ISSUE TITLE
SSH "quick connect" feature

### ISSUE THREAD

**Issue by mjs** [jumptrading/FluentTerminal#121]
I'd really like some kind of "quick connect" I could bring up with a key binding and then behave like the chrome address bar when it comes to remembering stuff I've typed in it before.

It would be powerful if "stuff" could be the full url, with options:

```
ssh://somehost
mosh://someuser@somehost
ssh://user@host? <not sure how to put -L options in here...)
```

**Comment by mjs** [comment]
Would it suffice to have a global keybinding which opens up FluentTerminal's current "SSH Connect" dialog? (i.e. it would even work if FT isn't currently focussed)

This combined with  #116 and #114 would get you most of the way there.

**Comment by enigmeow** [comment]
It would be pretty sweet to easily launch a new ssh terminal from anywhere...

**Comment by cjw296** [comment]
@mjs - not sure, the power for me is in hitting a keybinding and typing 3 characters of a hostname to bring up the full url I types before (most commonly ssh, maybe mosh, often some local shell config).

macOS terminal's dropdown:
![Uploading Screen Shot 2019-06-11 at 08.42.17.png…]()
...is better than nothing, but I think the chrome browser bar experience would be the best possible.

**Comment by enigmeow** [comment]
new-window-for-ssh-profile   is almost perfect..  If it remembered the last selected profile AND would select it when i hit return without having to tab to select,  I could literally hit the keyboard sequence and then return and I would have a new ssh window...

**Comment by cjw296** [comment]
Is "new-window-for-ssh-profile" in a .msi I could try out?

**Comment by enigmeow** [comment]
It occurs to me that looking at my usage pattern on xterm (what I am trying to migrate off of)... I tend to be logged into a machine and want to conveniently open another terminal to the exact same box... so, I tend to just type "xterm &" and a window shows up to the same box no matter how I got there.  So, to create the same effect... I'd want to be able to emit an escape sequence and then some url-quick-connect to specify the host/connection-params.. which the terminal emulator would (after enabling the feature) pick up and interpret to launch a window and connect into the box..

So, this quick-connect syntax could also be used there..

**Comment by mjs** [comment]
> Is "new-window-for-ssh-profile" in a .msi I could try out?

This should be in the newest [releases](https://github.com/jumptrading/FluentTerminal/releases)

**Comment by mjs** [comment]
> It occurs to me that looking at my usage pattern on xterm (what I am trying to migrate off of)... I tend to be logged into a machine and want to conveniently open another terminal to the exact same box... so, I tend to just type "xterm &" and a window shows up to the same box no matter how I got there. So, to create the same effect... I'd want to be able to emit an escape sequence and then some url-quick-connect to specify the host/connection-params.. which the terminal emulator would (after enabling the feature) pick up and interpret to launch a window and connect into the box..

It sounds like what you're after is a "duplicate this session" command (which has a key binding). Would that be sufficient?

**Comment by cjw296** [comment]
Could we split "duplicate this session" out into a separate issue?
The more we cycle around this the more I realise I value the macOS Terminal approach, came up again here: https://github.com/jumptrading/FluentTerminal/issues/117#issuecomment-503941165

**Comment by peske** [comment]
In my opinion, the initial reason for opening this issue is solved by implementing "Quick SSH".

Another thing mentioned by @cjw296 
> ...the power for me is in hitting a keybinding and typing 3 characters of a hostname to bring up the full url...
Is covered in https://github.com/jumptrading/FluentTerminal/issues/148

"Duplicate this session" feature should be covered by a separate issue (task) here.

Let's close this one?

**Comment by mjs** [comment]
"Duplicate session" discussion can now happen at #155. Closing this one.
