### ISSUE TITLE
I updated to 182 and after trying to uninstall/reinstall getting "specified account already exists"

### ISSUE THREAD

**Issue by enigmeow** [jumptrading/FluentTerminal#123]
After i was auto-upgraded to .182,  it could no longer launch the mosh/ssh process since it was looking in the previous location.  So, I uninstalled and on re'install, am now getting a "The specified account already exists" from the Terminal Installer

what account?  how do I remove it or get past this?

thank you

**Comment by MaxRis** [comment]
@enigmeow sounds like you should download and run MS tool to clean Registry for the specific msi records
https://support.microsoft.com/en-us/help/17588/windows-fix-problems-that-block-programs-being-installed-or-removed

**Comment by enigmeow** [comment]
issue fixed... :)
