### ISSUE TITLE
Mosh fails to start following FluentTerminal upgrade

### ISSUE THREAD

**Issue by mjs** [jumptrading/FluentTerminal#127]
Following an FT upgrade, Mosh connections fail to start with the following error:

![image](https://user-images.githubusercontent.com/14993/59639995-e4c68d80-91b0-11e9-8abe-47812a45ee23.png)

Rebooting the machine resolved the issue.

**Comment by mjs** [comment]
It turns out that restarting FluentTerminal or rebooting the machine **doesn't** actually help.

**Comment by peske** [comment]
Several things to check on the PC when it happens:
1. Does `mosh.exe` file exist at the specified path (`C:\Program Files\WindowsApps.....`);
2. Try to execute the whole command (`C:\Program Files\.......\mosh.exe user@host 60001:60999`) in a normal command prompt, and see if it works, or what kind of error it'll report.
3. It is x64 Windows, right?

With this info I'll be able to help.

**Comment by mjs** [comment]
@peske I think I've mostly got this figured out and will have a PR ready soon. The issue seems to be that the full path to mosh.exe (and ssh.exe) is being stored in the profile settings. For mosh.exe the path includes FT version number so it breaks when FT is upgraded.

**Comment by mjs** [comment]
https://github.com/felixse/FluentTerminal/pull/411 has merged so this should be fixed in jump master when the next merge from upstream happens.

Note that existing SSH profiles will fail on the next upgrade and have to be recreated. New SSH profiles won't have this problem.
