### ISSUE TITLE
Copy and paste does not work with tmux and a horizontal pane

### ISSUE THREAD

**Issue by daviesalex** [jumptrading/FluentTerminal#128]
Copy and paste works well inside mosh with tmux. However if you split the tab horizontally, it does not work (no obvious reason why). I'm using copy on select with the latest build. 

Note - its expected that copy and paste for multiple lines wont work if you split the tabs vertically; this issue is not about that!

**Comment by MaxRis** [comment]
Is not reproducible for me

![2019-06-22_2-45-40](https://user-images.githubusercontent.com/1928902/59956271-103ec600-9498-11e9-914e-ca97e60bbf4f.gif)

**Comment by daviesalex** [comment]
1. Launch EC2 instance - CentOS 7 (x86_64) - with Updates HVM - in region near you. I used t2.small instance.

2. Install latest Fluent terminal. In settings, mouse, enable copy on select. 

3. Connect via ssh (not mosh to remove a variable). 

4. Observe that copy paste works fine (run commands like top, dmesg, etc. to fill the terminal up)

5. Install tmux (yum install tmux)

6. Run tmux
tmux new-session

7. Split the panes
ctrl-b : split-window

8. Notice issue 1: the "separator" does not have a new line on it, i.e. it exports like this:
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────Jun 24 13:17:16 ip-172-30-2-2

Rather than 
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Jun 24 13:17:16 ip-172-30-2-2

9. Run commands in both windows

10. Close the lower window. 
cltr-b : kill-window

11. Create output in every line of the terminal (e.g. run dmesg)

12. Copy everything. Note that there is a newline missing from the middle row where the bar across the terminal previously was

**Comment by MaxRis** [comment]
@daviesalex can repro as it's described, thanks!

**Comment by MaxRis** [comment]
Described issue occurs with old WinPTY based session.
With ConPTY it copies everything in single line!
```
[    2.846516] scsi host1: ata_piix[    2.882849] ata1: PATA max MWDMA2 cmd 0x1f0 ctl 0x3f6 bmdma 0xc100 irq 14...
```

**Comment by MaxRis** [comment]
Will be resolved in upstream with merge of https://github.com/felixse/FluentTerminal/pull/421

**Comment by MaxRis** [comment]
Fixed by https://github.com/jumptrading/FluentTerminal/pull/141
