### ISSUE TITLE
Add support for preconfigured SSH hosts (C:\Users\username\.ssh\config)

### ISSUE THREAD

**Issue by peske** [jumptrading/FluentTerminal#132]
At the moment we are collecting all the data for SSH connection (username, host, port, etc.) from the user. But there's another option: user may add something like following in SSH config file (`C:\Users\username\.ssh\config`):
```
Host dev
    HostName dev.example.com
    Port 22000
    User johndoe
    IdentityFile ~/.ssh/the.key
```
After adding such entry to SSH config file, user can simply execute (in command prompt):
```
ssh dev
```
and he will connect without question asked.

Good thing about SSH config files is that they are standard, and can be shared between machines and OSes (Win, Linux, OSx). Another good thing is that many other options (like mentioned `LocalForward`) can also be added there.

We should probably add some support for such hosts.

Your thoughts guys?

**Comment by mjs** [comment]
From the perspective of providing an easy migration path for users that already have SSH config, as well as a way to support more esoteric configs, I like this. 

I'm a little concerned that this introduces yet another way to configure a SSH connection in FT. That would be 4: adhoc via the SSH Info dialog, SSH profile, SSH shortcut and now this. This means more code complexity and cognitive load for the user.

What would the UI look like for entries in .ssh/config? Would these entries just appear in the list of SSH profiles when the "New tab/window for SSH profile" commands are used?

**Comment by peske** [comment]
It's true that this is yet another way to configure SSH, thus may introduce some confusing. But the key difference is that this one, as well as `ssh://` links, are in a way core features of SSH, no matter the terminal app used. In other words, it isn't question if we will introduce some new features in Fluent, but it's more question if we will support common SSH features which are already there.

Regarding the implementation in Fluent: the easiest way would be to create a new, single-text-box dialog, where users will be able to manually enter all `ssh.exe` CLI arguments. Such simple single-text-box launch is already requested by @cjw296 in https://github.com/jumptrading/FluentTerminal/issues/117. 

For this particular case, the user would need to enter there only the name of the `Host` section from the config file (i.e. `dev`).

**Comment by peske** [comment]
After some additional analysis, it looks to me that this feature can be relatively easy embedded in our existing UI. We only need to add additional option into "Host" field - ability for the user to select from predefined hosts (in `[user_dir]\config` file), and prefill "Username", "Port" and "Identity file" based on the content of the selected host. In other words, the following config entry:
```
Host dev
    HostName dev.example.com
    Port 22000
    User johndoe
```
would match to `johndoe@dev:22000` in our existing UI.

Even more, the user can override some values (i.e. "Username", "Port" and "Identity file"), and create something like `otheruser@dev:22`, and it would still work! (I've tested.)

Now I'm quite sure that we should implement that.

**Comment by cjw296** [comment]
Okay, so from my perspective:
- I've never used "ssh shortcuts", whatever they are. They sound specific to Fluent and could/should go away.
- SSH config is standard, not sure I've ever used it, but would be good to support it.
- I actually find the multi-box form quite cumbersome to use to configure ssh, I wouldn't miss it if it went away, but I know that might not be true for others
- ssh:// links and a combo text box line macOS has would keep me happy (no surprise there ;-) ).

**Comment by peske** [comment]
Just to explain: "ssh shortcuts" are actually ssh links, but saved as shortcuts (i.e. on a desktop). Like any other desktop shortcut - double click and Fluent opens and connects wherever the link points.

**Comment by peske** [comment]
This is implemented by introducing "Quick SSH".
