### ISSUE TITLE
[ssh] prefix wrongly added to WSL tabs

### ISSUE THREAD

**Issue by MaxRis** [jumptrading/FluentTerminal#138]
It might started happen on recent changes in upstream.

![2019-06-26_16-07-29-wsl-tab-name-ssh-prefix-issue](https://user-images.githubusercontent.com/1928902/60182295-c0ac2180-982c-11e9-8d93-3781fd58c89c.png)

**Comment by MaxRis** [comment]
@peske could you please take a look at above issue

**Comment by peske** [comment]
Ahhh, yes... Will try to find an easy fix.

**Comment by peske** [comment]
Fixed in https://github.com/felixse/FluentTerminal/pull/424. Closing.
