### ISSUE TITLE
Presaved profile always starts with ConPTY turned on if launched by shortcut

### ISSUE THREAD

**Issue by MaxRis** [jumptrading/FluentTerminal#140]
Repro steps:

- Clonned CMD profile
- Turned off ConPTY, changed shortcut and saved changes
- New shortcut used to launch new tab

**Comment by peske** [comment]
I'm pretty sure that this one is already solved in https://github.com/felixse/FluentTerminal/pull/423. There I've changed view-models infrastructure.

You can try in `ap/unifyingvm`, or we can simply wait for the PR to be merged, and check afterwards.

**Comment by MaxRis** [comment]
@peske  thank you! it's not reproducible any more on our fork's latest release.
