### ISSUE TITLE
Add mosh "quick command" support

### ISSUE THREAD

**Issue by peske** [jumptrading/FluentTerminal#149]
At the moment we only support SSH in "quick command" feature. We need to add `mosh` support also.

Regarding this **we definitely need some input from Jump users**. The best input would be to provide **several examples of `mosh` commands** users would like to enter to "quick command" box. 

@cjw296, do you have any example?

**Comment by peske** [comment]
Here's the latest @mjs ' comment regarding this:

> Firstly, we don't want to accept `mosh-client`'s API. It's a low-level helper, not something that end users would normally interact with.

> Accepting arguments like the main `mosh` client makes sense as this will be most familar. Maybe our wrapper should be updated to behave more like standard mosh.

> Input from Jump folks on this would be much appreciated.

**Comment by cjw296** [comment]
@daviesalex is more of a mosh user than me, but I'd imagine the most important version would be `mosh <hostname>`. For the "quick connect" stuff, what's the plan for being able to launch local shells and docker shells quickly?

**Comment by peske** [comment]
@cjw296 , few questions for you:
- What you mean by "local shells"? Something like Mintty?
- Can you provide few examples of `docker` commands you would like to execute? Something like `docker exec -it <mycontainer> bash`?
It would be great if you can create a separate feature request here based on these answers. Let's keep this one for `mosh`.

**Comment by enigmeow** [comment]
Port forwarding X11 display :1.0 from the remote box to my local :0.0 x11 display

   ssh -R "*:6001:localhost:6000" remote-machine -N -f

This command works using the quick ssh feature but does not use the mosh functionality to keep the connection stable

**Comment by mjs** [comment]
I've moved the discussion about launching local shells to #153

**Comment by mjs** [comment]
> Port forwarding X11 display :1.0 from the remote box to my local :0.0 x11 display
> 
> ssh -R "*:6001:localhost:6000" remote-machine -N -f
> 
> This command works using the quick ssh feature but does not use the mosh functionality to keep the connection stable

@enigmeow I don't think it's even possible to use SSH port forwarding with Mosh. Or am I wrong about that?

**Comment by peske** [comment]
Done. Closing.
