### ISSUE TITLE
Ensure that all standard ssh link formats are handled correctly

### ISSUE THREAD

**Issue by peske** [jumptrading/FluentTerminal#15]
Microsoft recommends (and it makes sense) that if the app is registered to handle some protocol (`ssh://` in our case), it should handle all standard formats. We should ensure that this is the case. Currently it isn't - if `ssh://` contains some options which don't use, the app will reject it as invalid. It should be too hard to fix...

**Comment by nikitar020** [comment]
Why not just ignore those not used options?

**Comment by peske** [comment]
Now it does support standard `ssh://` link formats.
