### ISSUE TITLE
Add "Identity file" and "Use mosh" controls to "Quick command"

### ISSUE THREAD

**Issue by peske** [jumptrading/FluentTerminal#150]
Add "Identity file" and "Use mosh" controls to "Quick command" dialog.

This is based on @mjs' suggestion:

> That is, add the identity file controls and "Use Mosh" checkbox to the "Quick SSH" text field. Then:

> -  If the `-i` option is used in the command text field, update the identity file control. If the identity file control is updated, reflect this in the command line.
> - if the "use mosh" checkbox is enabled, change the command in the command text field and vice versa.

**Comment by peske** [comment]
Honestly speaking, I kinda don't like the solution suggested here. In my opinion, having two options which we already have ("full UI" and "custom command") is enough. People who prefer UI can use the first option, and those who like CLI can use the later one.

Creating a "custom command" with additional controls (combination of the two options we have) doesn't look useful to me.

But it's possible to implement! There will be some issues though, when we implement more commands (i.e. `mosh`), because it isn't `-i` option for identity files anymore, etc. But it's possible.

So it's important for us to hear your (Jump guys) opinion on that.

**Comment by cjw296** [comment]
Agreed, for the quick connect, I think of it almost like a one-command shell prompt, if I have to start checking boxes or selecting from dropdowns, we haven't succeeded.

**Comment by mjs** [comment]
The idea here wasn't that you *had* to use checkboxes or dropdowns but that you *could*, and that the command line and the UI would be integrated and stay in sync. So for example if you used the `-i` option in the command line, the UI controls for the identity file selection would also updated, and conversely if you used the UI controls, the command line would get updated to match.

This would avoid the need for separate UI and command-line modes and would help discoverability: by using the UI controls people would quickly learn what is possible in the command line field.

If no one likes the idea then I'm fine to drop it. It was just an idea to limit the number of ways of doing the same thing and to help people with learning how to use the command line.

**Comment by mjs** [comment]
@cjw296 your final thoughts on this would be appreciated

**Comment by cjw296** [comment]
That sounds very cool, and if it's doable without undue effort, I'd say go for it :-)
That said, it does sound complicated to implement, so I'd be happy with the two methods not being linked and just using one or the other...

**Comment by peske** [comment]
Knowing that "quick command" now supports many other shells than SSH and mosh, I believe that this one cannot be implemented in a meaningful way. @mjs, if you agree pls close this one.

**Comment by mjs** [comment]
Agreed. Seeing how Quick Launch works now, I don't think there's any need to do this.
