### ISSUE TITLE
Ability to quick launch local shells

### ISSUE THREAD

**Issue by mjs** [jumptrading/FluentTerminal#153]
On #149, the idea of generalising the "Quick SSH" feature to be able to open local terminal sessions and docker shell sessions was mentioned by @cjw296. Let's discuss this further here.

The Quick SSH feature was originally only intended for opening ad hoc SSH and Mosh connections but with a bit of work it could be extended to support opening all kinds of terminals. On the surface, this seems like a reasonable idea.

It could be done by leveraging existing shell profiles, so that `open <profilename>` would start a new terminal for that profile. Auto-completion could also be added to complete profile names.

As for docker or other other more exotic shells, I'm not sure that FT itself should have special support for them. How about sending any command that's not explicitly supported (i.e. not `ssh`, `mosh` or `open`) to a new terminal using the default shell profile?

**Comment by cjw296** [comment]
Yep, I'm after simple and generic here. I really like the "open" idea for profiles, but for docker and anything else, I'm totally fine with it basically being a text string that gets remembered in the freceny dropdown.

**Comment by cjw296** [comment]
@peske :
> @cjw296 , few questions for you:
> 
> What you mean by "local shells"? Something like Mintty?

Poweshell, cmd.exe, git bash to name a few.

> Can you provide few examples of docker commands you would like to execute? Something like `docker exec -it <myimage> bash`?

Yep, that's exactly it.

> It would be great if you can create a separate feature request here based on these answers. Let's keep this one for mosh.

I feel relatively strongly that we're looking for a single "quick launch" feature here, no matter what I'm doing, I just want to type a few characters and get to where I need to be.

**Comment by mjs** [comment]
This is now essentially a duplicate of #158. Closing this one as #158 has more detail.
