### ISSUE TITLE
Duplicate session command

### ISSUE THREAD

**Issue by mjs** [jumptrading/FluentTerminal#155]
Add a key binding which opens a new tab with a new session which duplicates the current session (i.e. same profile). This is especially useful when you want a new shell on the host you're currently SSHed in to.

Also add a "Duplicate Tab" option to the right click menu for the tab to access the same functionality.

**Comment by MaxRis** [comment]
Resolved by merging from upstream https://github.com/jumptrading/FluentTerminal/pull/191
