### ISSUE TITLE
"Quick Launch" feature

### ISSUE THREAD

**Issue by peske** [jumptrading/FluentTerminal#158]
It looks that initially created "Quick SSH" feature will evolve in more generic "Quick Command" feature, which will cover more local and remote commands (see also https://github.com/jumptrading/FluentTerminal/issues/153). Good news is that this shouldn't be too hard to implement. _Bad news_ is that there are quite a few questions to clarify before implementing:

- Probably this will assume separating "SSH Info" dialog and "Quick SSH". Or at least connecting these in a more meaningful way. Suggestions?
- Consequently it'll separate current "Remote Profiles" settings section, right?
- Should we create a new section in settings, something like "Command Profiles"?

Probably there will be more questions, but lets start clarifying these. Before going in discussion with the end users, probably we should make some plan / suggestions, so let's start with @mjs and @felixse opinions.

**Comment by felixse** [comment]
What would these Command Profiles do?
I would imagine this feature to be something like Ctrl+Shift+P in Visual Studio Code. A different dialog, disconnected from the SSH Info dialog.

**Comment by peske** [comment]
As far as I understand, the commands will do anything. The user should be able to enter any command with custom arguments, even ones that we already have in profiles (PowerShell, cmd.exe, ssh, mosh, etc.), but also another ones. I don't have the appropriate examples, but maybe something like Mintty, or entering Cygwin shell...

**Comment by mjs** [comment]
My 2 cents on how this should be done:
* separate out SSH Info from Quick SSH (sorry that you've only just merged them). 
  - This "Quick Launch" feature will allow everything that "Quick SSH" can already do and more
  - Keep "SSH Info" as a way to start SSH connections in a more beginner friendly way
* There's no need to significantly change the way Profiles and SSH Profiles work and there's no need to add "Command Profiles". 
  - Quick Launch will just allow users to start these profiles and more

Here's how I think the UX could work:
- User enters the Quick Launch shortcut
- Quick Launch command dialog appears with command input field focussed
- User types input and possible matching suggestions are provided in a dropdown
- As the user types more the suggestions are narrowed
- Suggestion matching should be case insenstive and use substring matching (match anywhere in the string)
- Suggestions should be ordered based on frecency and relevance. Start with something simple though - this can be improved over time.
- A specific suggestion can be highlighted using the the up and down arrow keys, with Enter to select it

More on suggestions:

- Profiles and SSH Profiles should be included in suggestions. For example if I have a local Profile called "WSL" and I type `ws` into the quick launch command, one of the suggestions should be "Start WSL session" (or similar).
- If the user enters a command starting with `ssh `, then there should be a suggestion to start a new session for the specified ssh command.
- If the user enters a command starting with `mosh `, then there should be a suggestion to start a new session for the specified mosh command.
- If the user types an arbitrary command, e.g. `dir -Recurse \foo\bar` then there should be suggestion to run that comand
  * Most commands will only make sense in specific shells so perhaps offer suggestions to run it in each (local) Profile, with the default profile sorted at the top of the list. So if I had a "WSL" profile as the default, and a "Cmd" profile and a "Powershell" profile the suggestion for some random command would be: "Run in WSL", "Run in Cmd" and "Run in Powershell".
- Suggestions should include command history. If the user enters part of a command that matches a previously run quick launch command, the previous command should be suggested. For example, if I had run `dir -Recurse \foo\bar` before and I type `foo` in the command field my previous dir command should be suggested.

Sessions started via Quick Launch should honour the "Open in windows/tabs" setting but there should be a way to override that setting on a per launch basis. Launching with Shift-Enter could force the session to open in a window, Ctrl-Enter could force open in a tab, with Enter opening the session according to the setting.

**Comment by mjs** [comment]
@cjw296 your feedback on the above would be much appreciated

**Comment by cjw296** [comment]
@mjs - apologies for the delay, your stuff above sounds absolutely perfect. Really like it!

**Comment by peske** [comment]
Majority of this issue is solved (done). Some advanced things still aren't implemented, like:

> If the user types an arbitrary command, `e.g. dir -Recurse \foo\bar` then there should be suggestion to run that comand

> Most commands will only make sense in specific shells so perhaps offer suggestions to run it in each (local) Profile, with the default profile sorted at the top of the list. So if I had a "WSL" profile as the default, and a "Cmd" profile, and a "Powershell" profile, the suggestion list for some random command would be: "Run in WSL", "Run in Cmd" and "Run in Powershell".

> Suggestions should include command history. If the user enters part of a command that matches a previously run quick launch command, the previous command should be suggested. For example, if I had run dir -Recurse \foo\bar before and I type foo in the command field my previous dir command should be suggested.

@mjs, if you agree we should create a separate issue for these advanced things, and close this one.

**Comment by mjs** [comment]
The core feature is done and the remaining issues have been captured by other issues now.  Closing this.
