### ISSUE TITLE
Create new window for teared off tab near mouse pointer on drop

### ISSUE THREAD

**Issue by MaxRis** [jumptrading/FluentTerminal#163]
Currently, new window for dropped out of the TabBar tab is positioned independently to the screen coordinates of drop event.
It's expected to have new window opened near mouse pointer on drop. (see Chrome or Firefox behavior).

**Comment by MaxRis** [comment]
Unfortunately, UWP doesn't provide API to move or set position of window.
Not sure how it's possible to implement desired behavior.

old link: https://stackoverflow.com/questions/31048576/uwp-window-placement
fresh: https://stackoverflow.com/questions/55656452/using-setwindowpos-with-uwp-or-metro-apps-has-no-effect

Also have checked [Window](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.window) class that provides read-only [Bounds property](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.window.bounds#Windows_UI_Xaml_Window_Bounds). In theory, UWP API should provide the way (but it doesn't) to set Bounds on create of new Windows [there](https://github.com/felixse/FluentTerminal/blob/e88fb78e9d1e481f968a1ceaa42889cb1c232976/FluentTerminal.App/App.xaml.cs#L552).

**Comment by mjs** [comment]
If it's not possible at this point then let's drop this for now.
