### ISSUE TITLE
Make tab dragging landing zone easier to find

### ISSUE THREAD

**Issue by mjs** [jumptrading/FluentTerminal#166]
From #109:

Finding the right place to drop a tab when reordering tabs is a little tricky. You do get used to it but it's hard at first. Can the zone where a tab can land be a little wider?
Similarly it's hard to figure out where the tab is allowed to land when dragging from another window. Can the entire tab row area be a landing zone? This is how web browsers do it.

From @MaxRis:
> Going to investigate this. That might be not easy to improve as well.
Current "wrong behavior" is that if you drop to another window, it always adds dropped item to the end of the list (but reordering inside same window works good).
Interesting that official [drag and drop sample](https://github.com/microsoft/Windows-universal-samples/tree/master/Samples/XamlDragAndDrop) has the same issue - dropped item is added into the end of the list.

**Comment by MaxRis** [comment]
This Issue is addressed in https://github.com/felixse/FluentTerminal/pull/478

**Comment by MaxRis** [comment]
Should be resolved by https://github.com/jumptrading/FluentTerminal/pull/170
@mjs could you please evaluate, thanks!

**Comment by mjs** [comment]
@MaxRis Much much better. Thank you!
