### ISSUE TITLE
Preserve terminal colours when moving tabs between windows

### ISSUE THREAD

**Issue by mjs** [jumptrading/FluentTerminal#167]
Right now the xtermjs serialize plugin doesn't preserve colours because xtermjs' output doesn't expose these. 

From @MaxRis on #109:

> It's turned out that colors information is not available via public xterm.js's API. Currently, only plain text from the buffer can be retrieved, but internally available _data https://github.com/xtermjs/xterm.js/blob/27d724a13aeb8366195caa965f9cd1442c211d31/src/common/buffer/BufferLine.ts#L56 can be used to get colors data per each cell.

> If we absolutely need this resolved, it should be possible to fork xterm.js and extend it with our own public API.

**Comment by MaxRis** [comment]
Roadmap for this might be following:
1. Xterm.JS should make cells' colours data to be accessible from plugins.
2. Serialization plugin should be update to construct terminal sequences with colours info included.

**Comment by MaxRis** [comment]
Feature request in Xterm.JS https://github.com/xtermjs/xterm.js/issues/2383

**Comment by peske** [comment]
I suggest ignoring this one because it'll be solved once we migrate to new `AppWindow` API (instead of `ApplicationView` used now).

**Comment by felixse** [comment]
This is resolved by https://github.com/felixse/FluentTerminal/commit/33bc06a36646c252bc1760c27d417cc8dee50935

**Comment by MaxRis** [comment]
@felixse thank you, it works great!
