### ISSUE TITLE
Preserve bottom line of terminal output when moving tabs between windows

### ISSUE THREAD

**Issue by mjs** [jumptrading/FluentTerminal#168]
From @MaxRis  on #109:

> Bottom status line seems is not get serialized because current logic serializes everything in buffer till the line with active cursor. Might makes sense to try to change the logic to RTrim all whitespaces and new lines.

**Comment by MaxRis** [comment]
Resolved by https://github.com/jumptrading/FluentTerminal/commit/afb50f1bdd88880412ee61ca899c5b1635aa8311
