### ISSUE TITLE
Quick Launch: deleting profiles from the completion list shouldn't be possible

### ISSUE THREAD

**Issue by mjs** [jumptrading/FluentTerminal#177]
Currently it is possible to remove Shell and SSH Profiles from the Quick Launch completion list. This doesn't actually remove them (and this is good) but it's misleading that they can even be temporarily removed. Have the Delete key do nothing for profile items.

**Comment by peske** [comment]
Solved in https://github.com/felixse/FluentTerminal/pull/486
