### ISSUE TITLE
CPU usage/battery life regression in recent builds

### ISSUE THREAD

**Issue by daviesalex** [jumptrading/FluentTerminal#180]
Needs a bisect. ? xterm.js rebase.

**Comment by daviesalex** [comment]
Updates:
- Cant reproduce on stock 1903 device
- At Jump, pretty reproducible (1809) from a bunch of people
- Bisected down to release 307, which had one systemtray change focused on audio muting - https://github.com/jumptrading/FluentTerminal/commit/4fd869d667a9aea6b0a75366d321da42f77e1134

**Comment by daviesalex** [comment]
We think this is basically a infinite loop:
`while (conhostProcessId == 0 && !cmdProcess.HasExited)
`
And this does a system call:
`                foreach (Process conhost in Process.GetProcessesByName("conhost"))
`

But I dont know much about this world, so we will wait for the commit author to jump in with thoughts! (its a mystery why we if the analysis above is good this issue is not seen on 1903 - ? a winpty vs conpty difference?)

**Comment by MaxRis** [comment]
I was not able to repro both on 1809 and 1903, but since such issues started occur it's no sense to keep "infinity" loops in the source code. Have rollback 3 seconds timeout and added more debug log messages in upstream PR https://github.com/felixse/FluentTerminal/pull/484

**Comment by daviesalex** [comment]
Confirmed that PR fixes this.
