### ISSUE TITLE
ability to disable update checks

### ISSUE THREAD

**Issue by cjw296** [jumptrading/FluentTerminal#183]
This is a tricky one. I know we want to keep everyone on the latest version, but I'm having some problems with the current auto-update experience:

- Something appears to block the fluent startup process. Given that this appears to take a lot longer when I'm on a mobile internet connection, my suspicion is that it's the update check.

- If there is a new version, dragging it down over a 3/4G connection that's already struggling with a VPN without any option to bail out doesn't sound like a lot of fun.

- If we end up with a problematic release, such as the recent tray-using-lots-of-CPU issue, we currently have no way to prevent being auto-updated to that release.

My preference would be for the auto-update to be more like Chrome's: warn me about a new release and put a non-dismissable nag box somewhere in the tab bar.

If we really need it, some timeout in days or weeks, that forces people to update.

**Comment by MaxRis** [comment]
Do you have startup delay even if auto updates are turned off in Settings? App still requests GitHub for latest version to show the dialog box if new version is available.

![2019-08-15_10-57-50-auto-updates-turned-off](https://user-images.githubusercontent.com/1928902/63083220-df878400-bf50-11e9-95cd-8dca12cc6191.png)

**Comment by daviesalex** [comment]
Please dont spend time on this. We are hopefully weeks away from killing this MSI entirely and moving to deployment via the Windows store (at which point the Jump fork can die).  All this code can come out at that point; that system will handle the update checking/installing with no prompts. In the short term, you can always stop a bad install from running by clicking "No" at the UAC prompt.

**Comment by cjw296** [comment]
Didn't know there was a setting, that's exactly what I was looking for :-)

**Comment by cjw296** [comment]
Actually, that "automatically download and install updates" option doesn't work. I had it turned off, but still getting auto-updates...

**Comment by MaxRis** [comment]
@cjw296 could you please give more details regarding what issues it causes for you when this option is turned off?
It should just display dialog box on start and prompt that new update is available. The check for update is async and shouldn't increase startup time.

**Comment by cjw296** [comment]
Maybe I'm misunderstanding what this does, I may also be short on sleep. So with this off, I should still get the modal dialog box saying there's a new version, but I can hit no/cancel/whatever if I don't want it?

**Comment by MaxRis** [comment]
Yes, if this option is off, you will receive following notification on new update available (but download and installation will not start at all if you press "Cancel") :

![2019-08-16_13-29-57-update-notification](https://user-images.githubusercontent.com/1928902/63161988-239a8780-c02a-11e9-80de-f6ad8e1a8511.png)

Please let me check application startup time on 2g mobile internet locally. I can imagine that WebView might request something from Internet during load of XTerm.JS JavaScript bundle.

**Comment by MaxRis** [comment]
I have tried on slow 2g connection and there is no significant difference for me in startup time of the application.
@cjw296  additional thing to consider: if you are on battery, might it be automatically reduced performance of your laptop system causes app start longer?

**Comment by daviesalex** [comment]
Please do not spend time on this - this entire feature will be ripped out very soon.
