### ISSUE TITLE
Quick launch should expand/search commands as well as profile names

### ISSUE THREAD

**Issue by cjw296** [jumptrading/FluentTerminal#186]
Loving quick connect, but it looks like currently it only searches through profile names and previously types quick commands.

Could it also search through the command that would be launched from the profile?

Use case: I have some really long `docker run` profile commands, and sometimes I want to launch them but having slightly edited the command. It'd be great to have quick connect search through profile names and profile command, and when matching on the latter, actually put the text of the command in the quick launch box.

**Comment by mjs** [comment]
Seems reasonable. Another one for @peske when he's back.

**Comment by mjs** [comment]
One thing to watch out for here is how much including profile commands will clutter the completion list. I guess we'll see.

**Comment by cjw296** [comment]
Yep, agreed on the clutter. I mean, the correct-but-annoying-to-implement answer is that when a command from a profile is matched, it's the frecency of the profile that's updated and the actual command is only added to the completion list if it's changed at all...

**Comment by cjw296** [comment]
Not that important.

**Comment by peske** [comment]
This one is quite easy to implement. I wouldn't need more than 3-4 hours to implement. So if you change your mind...
