### ISSUE TITLE
"Highlight All" search option

### ISSUE THREAD

**Issue by cjw296** [jumptrading/FluentTerminal#189]
I could have sworn we had a ticket for this already, but please can we implement "search within buffer".

Matching Chrome's Ctrl-F behaviour would be the gold standard for me.

**Comment by MaxRis** [comment]
Done :) CTRL+SHIFT+F
![2019-08-15_19-18-06-search](https://user-images.githubusercontent.com/1928902/63109412-d9fe5e00-bf91-11e9-94fe-89db4a151e3c.png)

**Comment by cjw296** [comment]
Oh, wait, one thing missing from chrome: "highlight all" showing their locations as yellow lines in the vertical scrollbar. Would that be possible?

**Comment by MaxRis** [comment]
@cjw296 currently searching is done internally by XTerm.JS and Fluent just use JavaScript API provided by XTerm.JS. We will need to check if there is any API for "highlight all".

**Comment by MaxRis** [comment]
XTerm.JS doesn't have API for "Highlight All" functionality. But they are aware about adding it https://github.com/xtermjs/xterm.js/issues/1653 .

@cjw296 but XTerm.JS provides possibility [to search with options](https://github.com/xtermjs/xterm.js/blob/master/addons/xterm-addon-search/typings/xterm-addon-search.d.ts#L12): "search term is a regex", "search for a whole word", "search is case sensitive" and "incremental search, this will expand the selection if it still matches the term the user typed. Note that this only affects `findNext`, not `findPrevious`."

How do you feel about adding above search options support?

**Comment by cjw296** [comment]
"search with regex" would be nice, but not critical. Don't care about the others, case-insensitive phrase search is the most important one by far, and we have that now :-)

**Comment by cjw296** [comment]
No that important.

**Comment by felixse** [comment]
options for case sensitive, whole word and regex are now implemented
