### ISSUE TITLE
crashes

### ISSUE THREAD

**Issue by cjw296** [jumptrading/FluentTerminal#194]
I've had a selection of crashes moving from one dock, to undocked, to another dock.
I've also had at least one crash just in use.
My patterns are normally one or two git bash shells, 3-5 docker run shells and one or two ssh shells.

**Comment by cjw296** [comment]
Logs from one of the dock/undock crashes:

[fluentterminal.systemtray20190819.log](https://github.com/jumptrading/FluentTerminal/files/3524916/fluentterminal.systemtray20190819.log)
[fluentterminal.app20190819.log](https://github.com/jumptrading/FluentTerminal/files/3524917/fluentterminal.app20190819.log)

**Comment by cjw296** [comment]
These logs cover the "crashed will working" one:

**Comment by MaxRis** [comment]
@cjw296 thanks, second `systemtray.log` caught something interesting.

**Comment by MaxRis** [comment]
Known crash: Closing of not yet initialized tab causes null reference access exception.

**Comment by MaxRis** [comment]
Reported crash was resolved with https://github.com/felixse/FluentTerminal/pull/510.
Others known crashes were resolved in scope of this Issue as well.

**Comment by cjw296** [comment]
Just updated to 1.1.347.0, fingers crossed!
