### ISSUE TITLE
hang on startup

### ISSUE THREAD

**Issue by cjw296** [jumptrading/FluentTerminal#199]
I have my default shell set to a local git bash session.
Frequently, on starting fluent, the session just hangs.
I'll stick a screenshot and logs in the slack channel.

**Comment by MaxRis** [comment]
I guess complete hanging is related to the recently resolved issue with hanging on terminal resizing.
I have setup similar git bash profile as default and can't repro.
@cjw296 could you please update this ticket if you will see again hanging of terminal on the startup in near future, thank you
