### ISSUE TITLE
Associate ssh:// and mosh:// URLs with FluentTerminal

### ISSUE THREAD

**Issue by mjs** [jumptrading/FluentTerminal#2]
Have a way, preferably done as part of installation, to set up url handlers for mosh:// that feed through to Fluent such that it opens a new shell in a new tab and makes a mosh connection to the host and optional user specified.

More here: https://msdn.microsoft.com/en-us/windows/desktop/aa767914

**Comment by mjs** [comment]
It looks like this actually much easier for UWP apps.

**Comment by MaxRis** [comment]
That's done in our fork
