### ISSUE TITLE
Feedback is missing if SSH or Mosh connection fails

### ISSUE THREAD

**Issue by mjs** [jumptrading/FluentTerminal#20]
If a SSH or Mosh connection fails (e.g. if server requires a cert but you don't have it) then the connection fails without any feedback to the user. This is confusing and hard to debug.

One approach could be to show the tab with whatever output the SSH/Mosh client generated rather than closing it.

**Comment by mjs** [comment]
This (incomplete) branch helps with this: https://github.com/jumptrading/FluentTerminal/tree/leave-tabs-for-failed-shells

**Comment by MaxRis** [comment]
PR to introduce process exit code saving and handling merged into upstream https://github.com/felixse/FluentTerminal/pull/343 and merged back into our fork

**Comment by MaxRis** [comment]
PR https://github.com/jumptrading/FluentTerminal/pull/49 with changes to not close terminal tab if shell process was exited with error code is merged into fork

**Comment by peske** [comment]
Hah, now I know why tabs are not closing when underlying process exits with non-zero code! :)

**Comment by mjs** [comment]
This is fixed now that tabs stay open.
