### ISSUE TITLE
Ctrl-Enter to immediately run a quick launch command

### ISSUE THREAD

**Issue by cjw296** [jumptrading/FluentTerminal#200]
From #185: 

When I hit enter in the quick connect box, I expect the terminal to be launched. Currently, I have to hit enter again, which feels a bit weird.

On the assumption that the Advanced section isn't the usual flow, I'd be fine with "hitting enter once" going through. If you want to use advanced stuff, use tab or click with the mouse.

I think this UI pattern is pretty common and feels natural to people as it's what web apps and the like have been doing for years.

**Comment by mjs** [comment]
@peske would this be hard to implement?

**Comment by mjs** [comment]
It turns out it's surprisingly difficult to override the behaviour of Enter in UWP. 

Changing tack slightly - we are going to see if Ctrl-Enter can be used as the "run now" binding as a middle ground.

**Comment by peske** [comment]
I've found and implemented (https://github.com/felixse/FluentTerminal/pull/582) the most intuitive solution in my opinion:

Selecting a suggested text from auto-complete list in "Quick Launch" now works as follows:
- Selecting with `Enter` key immediately closes the dialog and launches the command;
- Selecting with `Tab` key selects the command and moves focus to the next control ("Advanced Options");
- Selecting with mouse click / tap selects the command, and the command text box retains focus.

Closing this one.
