### ISSUE TITLE
quick launch only works when the body of a tab is selected

### ISSUE THREAD

**Issue by cjw296** [jumptrading/FluentTerminal#208]
Steps to reproduce:
- click menu to open
- click menu again to close
- hit key binding to "quick launch new tab"

Nothing happens. You have to select the body of the active tab for it to work.

Desired behaviour for me would be to have the key bindings work whenever a Fluent window is active.

**Comment by peske** [comment]
Implemented in https://github.com/felixse/FluentTerminal/pull/578
