### ISSUE TITLE
Too long few second delay to accept input after terminal window was resized

### ISSUE THREAD

**Issue by MaxRis** [jumptrading/FluentTerminal#213]

**Comment by mjs** [comment]
This delay helps to prevent corruption of the terminal during window resizes. Play around with reducing the delay by all means but the shorter the delay the higher the chance of buffer corruption.

We're in this situation due to the asynchronous way that resize events are delivered.

**Comment by mjs** [comment]
I think that @peske reduced this timeout recently.

**Comment by peske** [comment]
This is fixed long time ago.
