### ISSUE TITLE
UI latency seems to have increased

### ISSUE THREAD

**Issue by mjs** [jumptrading/FluentTerminal#217]
There have been reports about UI latency not being as good as it used to be. 

Try to reproduce and hunt through Git history to see when things got worse.

**Comment by mjs** [comment]
Prioritise this work after bugs, memory leaks and stability issues

**Comment by mjs** [comment]
I wonder if this was to do with $TERM being set to xterm-256color, which is known to slow things down.

**Comment by daviesalex** [comment]
For what its worth, I just tried the latest build and based on my totally scientific personal opinion/hunch, I think we are back to as good as its ever been. Since I think I was the original reporter here, i'm going to close this out.

**Comment by MaxRis** [comment]
There was a change by Felix to eliminate websocket from communication chain https://github.com/felixse/FluentTerminal/pull/522
Some communication complexity was reduced and startup time also should be improved with above change.
