### ISSUE TITLE
laggy when running tmux on an ssh session

### ISSUE THREAD

**Issue by cjw296** [jumptrading/FluentTerminal#218]
If I cat a file in a tmux session on a remote host that I've ssh'ed to using Fluent, it's really slow and laggy compared to cat'ing the same file on the same host if tmux isn't in play.

I don't experience this difference when using other ssh/shell software.

**Comment by cjw296** [comment]
Could well be related to #120

**Comment by daviesalex** [comment]
This may well be more https://github.com/jumptrading/FluentTerminal/issues/120 than tmux

**Comment by cjw296** [comment]
When #219 is fixed, I'll see how I fare with ConPTY turned off.

**Comment by mjs** [comment]
@cjw296 Now that #219 is fixed, does switching off ConPTY help?

**Comment by cjw296** [comment]
I'm afraid not. Over a plain SSH connection, it's snappy. Once I'm in a tmux session, it's slow and jerky.
Was there some xterm setting I was supposed to set? Almost certain I haven't done that and happy to see if that makes a difference.

**Comment by daviesalex** [comment]
@cjw296 can you run echo $TERM in a terminal and paste the output?

**Comment by cjw296** [comment]
In ssh:
```
[cwithers@ljoit-cwl2 ~]$ echo $TERM
xterm-256color
```
In tmux:
```
[cwithers@ljoit-cwl2 ferrari]$ echo $TERM
screen
```

**Comment by cjw296** [comment]
Just to record it here, I tried setting `TERM=xterm` in .basrhc and starting a new tmux session in a new ssh session, and I'm afraid the lagging cat'ing of a long log file is still there.

**Comment by wrigtim** [comment]
+1 (this is the main issue that stops me using as my daily-driver)

**Comment by MaxRis** [comment]
@cjw296 @wrigtim could you please share the size of terminal and the size files you are trying to `cat`?

**Comment by MaxRis** [comment]
I'm having fully opposite experience so far:

- cat for long file (47 MB text file) via plain `ssh` works with the same speed in Fluent as from standard `cmd.exe` shell.
- cat from `tmux` under `ssh` speed up things as its run on host natively or even faster

**Comment by cjw296** [comment]
@MaxRis / @wrigtim - what Windows version are you on?
@jdconti doesn't have this issue, and he's on 1903.
Weirdly, mine is even slower now that I'm in a different office to the linux box I'm tmux'ing to.
Most weirdly of all, if I have two ssh sessions connected to the same tmux, and the other one is via another ssh client (chrome ssh app in my case...), this speeds up the one in Fluent...

**Comment by MaxRis** [comment]
Have 1903 Build 18362.418

**Comment by MaxRis** [comment]
@cjw296 if upgrade to 1903 solves the issue than it's one more reason to upgrade.

**Comment by peske** [comment]
I cannot reproduce this one on Win 1909. I have 50 megs text file, and in `ssh`+`tmux` session I can `cat` it for about second or so.

**Comment by cjw296** [comment]
1903 fixes this I think :-)

**Comment by peske** [comment]
I'm very confused with the fact that Windows version can influence such things! Anyway, great if it works now.
