### ISSUE TITLE
Replace ApplicationView API with the new AppWindow API

### ISSUE THREAD

**Issue by peske** [jumptrading/FluentTerminal#220]
In 1903 Microsoft has introduced a new [`Windows.UI.WindowManagement`](https://docs.microsoft.com/en-us/uwp/api/windows.ui.windowmanagement) namespace and [`AppWindow`](https://docs.microsoft.com/en-us/uwp/api/windows.ui.windowmanagement.appwindow) API. The key difference comparing to the existing [`Windows.UI.ViewManagement`](https://docs.microsoft.com/en-us/uwp/api/windows.ui.viewmanagement) namespace and [`ApplicationView`](https://docs.microsoft.com/en-us/uwp/api/windows.ui.viewmanagement.applicationview) API (we are currently using) is that in the new API we have ability to select UI thread of the new windows. This allows us to move content (tabs) between the windows seamlessly.

Here's a [demo](https://www.youtube.com/watch?v=HVl9QsaowTg) which shows moving a tab with `WebView` in it between the windows.

The main benefit of introducing the new API in FT is in avoiding Xterm serialization, thus reducing _error surface_ (chance for bugs).

Replacing the API will take some time (rough estimation 2 full weeks), so here I'm opening the idea for cost/benefit discussion.

**Comment by mjs** [comment]
Ultimately this feels like the more "correct" solution but the fact that it's 1903 only, and in preview, and has many limitations (I hope that most will be resolved as it becomes stable), means that I don't think we should do anything with this right now.

Something this big would also need approval from @felixse

**Comment by felixse** [comment]
Maybe in a year, but I don't think we should do this right now. 1903 is still relatively new (don't even have this one on my computer at work), the API is still in preview, and we would need to increase the minimum version by 3 semi-annual updates. I don't think the issues with tab&drop are so severe that we need to do this.

**Comment by mjs** [comment]
Closing this for now.
