### ISSUE TITLE
ability to reconnect dead ssh sessions

### ISSUE THREAD

**Issue by cjw296** [jumptrading/FluentTerminal#222]
A nice to have, rather than a blocker, but that I miss from the Chrome SSH app is the ability to reconnect dead ssh sessions.

I have a bunch of tabs open with ssh sessions, when I move from home to work, they die. I currently have to close and re-open them all. Would be great to be able to "reconnect all" somehow, or at least have a thing in each tab I could press to reconnect the dead session.

Nice to keep the shell history when this happens if possible, can then just pick up where I left off.

**Comment by peske** [comment]
As far as I know SSH simply cannot be reconnected. Maybe you can use `screen` to help you with that.

Regarding opening last session in FT (with all the tabs that were opened when FT was closed), it's possible to implement, but the tabs will require you to authenticate again (where applicable), and effectively you'll get new sessions (not previously opened ones).

**Comment by cjw296** [comment]
This is how the Chrome SSH app does this: 

<img width="397" alt="2019-12-02 11_54_49-cwithers@ljoit-cwl2__" src="https://user-images.githubusercontent.com/632049/69957616-e683d380-14fa-11ea-9fd7-61b14b4bdfbb.png">

(Note the `(R)econnect, (C)hoose, E(x)it line.)

I'm not fussed on the detail of the implementation, whatever is easiest to implement (text line Chrome SSH app, button in tab bar, whatever). But it would be really nice to re-use the window that's already there and, hopefully, keep the scrollback buffer that was there already.
