### ISSUE TITLE
Default to WinPTY settings option

### ISSUE THREAD

**Issue by MaxRis** [jumptrading/FluentTerminal#223]
Since ConPTY doesn't support such functionality as mouse mode it makes sense to have global settings option to force usage of WinPTY by default.

**Comment by mjs** [comment]
There used to be a global option like this which I think was later removed upstream.

What would this option affect? The default ConPTY/WinPty option value for new profiles and adhoc commands?

**Comment by MaxRis** [comment]
Yes, I think it should affect all places where we have possibility to turn on/off ConPTY.

**Comment by mjs** [comment]
> Yes, I think it should affect all places where we have possibility to turn on/off ConPTY.

You may want to talk to @felixse about this because FT used to have this exact option but it was removed for some reason.

**Comment by MaxRis** [comment]
Merged into upstream
