### ISSUE TITLE
Implement other encodings besides UTF8

### ISSUE THREAD

**Issue by peske** [jumptrading/FluentTerminal#225]
It looks that FT currently encodes all user input in UTF8. We should extend this to support other encodings to, like Unicode.

**Comment by mjs** [comment]
Unicode isn't an encoding right? UTF-8 is just one way of representing unicode characters.

**Comment by peske** [comment]
@mjs : It's probably terminology-related misunderstanding, but .NET has them separately. In fact, here's the list of encodings available in .NET:

```
Encoding.ASCII
Encoding.BigEndianUnicode
Encoding.Unicode
Encoding.UTF32
Encoding.UTF7
Encoding.UTF8
```

But it this isn't the point. The point is should we allow other encodings or not. At the moment we only have **hard-coded** `UTF8` encoding. Do we need other encodings? I don't know - it's something that users should tell. As far as I know, pound sign (£) which caused an issue to Chris should be supported in `UTF8`, but some other things (i.e. Chinese letters, Cyrillic alphabet, etc.) maybe aren't. Do we need them? Again, it isn't my call to make.

But thing that I'm sure is that we can implement these rather easily, in day or two, in a similar way we have LF/CRLF implemented. Session level encoding can default to `UTF8`, but user will be able to select another from a drop down list.

**Comment by peske** [comment]
The key thing though is to ensure that the underlying CLI process (i.e. SSH, CMD, PS, etc.) does support the selected encoding. But at the end of the day we can leave this on users - it'll be in "Advanced" section anyway :).

**Comment by peske** [comment]
Not sure about this one anymore. It looks that xterm.js also uses UTF8. It'll require deeper investigation on encoding / locales if we want to solve this one.

**Comment by mjs** [comment]
Closing as this is unlikely to happen

**Comment by peske** [comment]
I suggest leaving this open because I believe that I can solve it in few days of work.

**Comment by mjs** [comment]
Really? What about the issue that xterm.js may only use UTF-8 and that mosh is UTF-8 only?
