### ISSUE TITLE
Command history options stuck to values used with the first execution

### ISSUE THREAD

**Issue by peske** [jumptrading/FluentTerminal#233]
It's a bug noticed by @mjs:

> One thing I've noticed with this is that once a command is in the history any changes in options when it is next re-run don't update the saved history. That seems a little strange - it means you are stuck with whatever options you set when the command was first run. Shouldn't they update each time the command is run?

**Comment by peske** [comment]
I've just checked, and it looks that there's no bug. When a quick command is used, options are set to their **last** value (not the initial one). For example, execute something like `mosh user@host` and set tab color to Green in advanced options, then logout. After that execute the same command, but change tab color to Orange, and logout. Execute the same command again, without touching advanced options, and you'll get orange tab.

Exceptions are saved profiles - Shell Profiles and SSH Profiles configured in settings window. Quick Launch dialog **does not change pre-created profiles**. In my opinion it would wrong to change these profiles in such transparent way.

**Comment by mjs** [comment]
You're right. I've tried with the latest build and I don't see the issues. It was either fixed in a later release or I was selecting a profile and not a historical command. Agreed that we shouldn't update pre-defined profiles.
