### ISSUE TITLE
Recheck / improve locking patterns in XtermTerminalView

### ISSUE THREAD

**Issue by peske** [jumptrading/FluentTerminal#238]
I've noticed bit suspicious locking flow in XtermTerminalView class: it uses few locks / semaphores. I believe that it can be improved. I'm pretty sure that this issue is reason for a strange FT behavior when new Powershell/CMD tab is opened: you've probably noticed that sometimes output is initially missing until user enters something (`Enter`), and then everything appears as if it was flushed from some buffer. Not big deal though, but it can be fixed in few working hours probably.

I won't start with this without approval from stakeholders.

**Comment by mjs** [comment]
This is worth dealing with, especially if it fixes the missing output on startup (this happens every time for me). Go for it.

**Comment by peske** [comment]
I've changed everything that I've planned (see referenced PRs above). In my opinion it's much better now because all the semaphores and `BlockingCollection` are removed, resizing is more responsive and more reliable, etc.

But it looks that this still doesn't solve the issue with the missing output on session start (described above). It looks that it still happens time-to-time. Obviously my guess that it's caused by the locking was wrong. If we want to address this issue we should search in other places. Maybe in SystemTray proj? Not sure...

It may happen that these changes also solve some other resizing issues spotted so far. Feedback will be welcomed once the changes are in production.

**Comment by peske** [comment]
Again, did everything I planned. Closing.
