### ISSUE TITLE
Inconsistency with open in new window / new tab

### ISSUE THREAD

**Issue by peske** [jumptrading/FluentTerminal#244]
Here's how menu looks like now, if "Open new terminals as" option is set to "Tabs":
![image](https://user-images.githubusercontent.com/6330857/69541552-b03dd580-0f89-11ea-9168-19917818825d.png)

Here's how it looks if we change the option to "Windows":
![image](https://user-images.githubusercontent.com/6330857/69541614-d95e6600-0f89-11ea-8619-ada67eba02f5.png)

As you can see, the keyboard shortcuts are different. This is because we have different keyboard shortcuts for opening the same thing in tab and window. For example, shortcut for opening the default profile in new tab is `Ctrl+Shif+T`, while for opening the default profile in new window it's `Ctrl+Shift+N`.

I think that it (different shortcut for the same item) may be confusing for the app users.

What I wanted to suggest is to remove such duplicated shortcuts completely. We should simply have "default profile" shortcut, and it should open tab or window based on "Open new terminals as" settings value. Actually current profile shortcuts (i.e. "Powershell" profile `Ctrl+Alt+1`) work just like like that.

**Comment by felixse** [comment]
I'm still not convinced that we should eliminate the new tab/new window submenus. And I don't think we should remove these keybindings. It's quite standard to have keybindings like this. 

The idea behind the "open new terminals as" option was to set a default for terminals that are requested from the outside (like cli, explorer integration, etc.).

With the menus for new tab/new window we wouldn't need to deal with confusing keybindings like this.

Also "Default Profile" makes it hard to imagine what happens if you click it. Does it create a new default profile? There is no context that this will open a new tab or window.

**Comment by peske** [comment]
@felixse all this is your call. I'll simply try to help you with some arguments:

> I'm still not convinced that we should eliminate the new tab/new window submenus.

I strongly suggest eliminating them because this way you would hide core features (shell terminals) behind a secondary feature (tab/window). To magnify: imagine having tab/window menus, than theme submenu, then tab color submenu, then finally shell.

> And I don't think we should remove these keybindings. It's quite standard to have keybindings like this.

OK. I've just noticed that it's inconsistent with profile shortcuts behavior, but not big deal.

> Also "Default Profile" makes it hard to imagine what happens if you click it. Does it create a new default profile? There is no context that this will open a new tab or window.

Let's change it! "Default Shell"? "Launch $profile_name"? Something else? Just please don't name it "New Tab" / "New Window" - this is ultra confusing. Although user would know that he'll get tab/window, he wouldn't have a clue what it will contain.

>

**Comment by peske** [comment]
I've changed "Default Profile" with the actual profile name:
![image](https://user-images.githubusercontent.com/6330857/69602695-bdee6c00-1018-11ea-9a95-b3892ac82e6f.png)

As everything else there, it also updates dynamically.

**Comment by mjs** [comment]
Resolved in https://github.com/felixse/FluentTerminal/pull/595/
