### ISSUE TITLE
can't ctrl-c in the middle of cat'ing a long file

### ISSUE THREAD

**Issue by cjw296** [jumptrading/FluentTerminal#250]
#90 might be thing but wanted to log this, so, as of the latest .4 release:

conpty=off: not sure this works at all

conpty=on, ssh: doesn't work, can't ctrl-c cat'ing of a long fine
conpty=on, mosh: does work.

**Comment by MaxRis** [comment]
It's turned out that this is seems the Fluent's issue and fully related to the https://github.com/jumptrading/FluentTerminal/issues/250 which describes the same issue, but in general.

**Comment by MaxRis** [comment]
1. Open wsl shell in Fluent and `cat -v` some binary big enough file ( ~50 MB is fine ).
2. Open another tab in Fluent and send `CTRL+C` command. Noticeable delay will happen before Fluent will react on `CTRL+C`.  Thus it's caused by https://github.com/jumptrading/FluentTerminal/issues/250

**Comment by MaxRis** [comment]
duplicate of https://github.com/jumptrading/FluentTerminal/issues/258
