### ISSUE TITLE
Terminal crashes on tab detach

### ISSUE THREAD

**Issue by peske** [jumptrading/FluentTerminal#255]
The issue reported by @MaxRis, affects the current upstream master (not in our release package yet luckily). It's caused by https://github.com/felixse/FluentTerminal/pull/619. Funny, but the previous buggy implementation (or at least I thought that it's buggy) was doing a better job.

Here's the exception:
```
System.Exception: A COM call to an ASTA was blocked because the call chain originated in or passed through another ASTA. This call pattern is deadlock-prone and disallowed by apartment call control.
```
In other words, `TermnalBridge.Output` event cannot be triggered from the UI thread after drag/drop. The thing is that drag/drop does change UI thread (different views have different UI threads), but it looks that somehow `TerminalBridge` still uses the previous UI thread (or something like that).

Nevertheless, it looks that `TerminalBridge.Output` doesn't need to be called from UI thread. It can be simply triggered from any thread.

**Comment by MaxRis** [comment]
It should be a duplicate of https://github.com/jumptrading/FluentTerminal/issues/254
Sorry that haven't notified directly, but I though you should receive emails about creation of new issues.

**Comment by peske** [comment]
I've closed another one as duplicate :) Reopening this one. Anyway, it's solved so I'll close it again in minutes.

**Comment by peske** [comment]
Fixed in https://github.com/felixse/FluentTerminal/pull/627. Closing.
