### ISSUE TITLE
Terminal selection brush issue

### ISSUE THREAD

**Issue by maxhora** [jumptrading/FluentTerminal#256]
![2019-12-13_14-38-53-selection-brush-issue](https://user-images.githubusercontent.com/1928902/70794511-34c88a80-1db7-11ea-95aa-d8a31d1dc52b.jpg)

Text selection is highlighted with brush of wrong color (without transparency).

The issue doesn't happen after new theme is applied from the Settings menu.

Probably, related to recent changes there https://github.com/felixse/FluentTerminal/commit/e559c3ee382077cf34ee4e170f08a53efac86b83

**Comment by felixse** [comment]
related to https://github.com/xtermjs/xterm.js/issues/2620
I'm on it

**Comment by MaxRis** [comment]
It sounds like we should consider rollback of xterm.js to previous version without the issue ( the fix seems still is not available ).

**Comment by MaxRis** [comment]
XTerm.JS team supposes to fix the issue in the upcoming 4.4.0 release scheduled for 6th of Jan.

**Comment by MaxRis** [comment]
The issue still exists with Xterm.JS 4.4.0-beta.15

**Comment by felixse** [comment]
Created an upstream issue: https://github.com/xtermjs/xterm.js/issues/2736

**Comment by MaxRis** [comment]
@felixse thank you!

**Comment by maxhora** [comment]
That is resolved by @felixse in Fluent's master with forked custom build of xtermjs.
