### ISSUE TITLE
Decreasing of font size with CTRL+SHIFT+- below "supported minimum" crashes UWP process

### ISSUE THREAD

**Issue by MaxRis** [jumptrading/FluentTerminal#265]
Crash is constantly reproducible on latest 0.6.1.4 "local" build

reported by @cjw296

**Comment by MaxRis** [comment]
Crash happens in Window's internals on "zoom-out" event triggered for UWP's WebView control.
Zooming of WebView's content happens on while pressing CTRL+SHIFT+"+/-" or while holding CTRL and scrolling a mouse wheel.
Unfortunately, there is no way to disable zoom functionality in UWP's WebView ( only zooming by touch gesture can be disabled ) and adjusting of different [MS specific CSS properties](https://docs.microsoft.com/en-us/previous-versions/jj127332%28v%3dvs.85%29) haven't helped as well.
The issue should disappear after Fluent will start Chromium based web view control usage.

**Comment by mjs** [comment]
@MaxRis Have you exhausted all options that you can think of? Would it be helpful if @peske had a look at this?

**Comment by MaxRis** [comment]
@mjs yes, I've tried different things (related to my above comment https://github.com/jumptrading/FluentTerminal/issues/265#issuecomment-581131895 ).
Sure, would be awesome if @peske will check it as well.

> only zooming by touch gesture can be disabled

Corresponding CSS property https://docs.microsoft.com/en-us/previous-versions/hh771891%28v%3dvs.85%29 already in the Fluent's source code, it also makes me think that @felixse was aware about not desired zooming behavior. But, seems, it disables only touch gesture, unfortunately.

**Comment by MaxRis** [comment]
Some more details:

- Changing the default FontSize from `FontSize = 13,` (in DefaultValueProvider.cs) to `19` and up "fixes" the crash. Zooming out at maximum doesn't decrease font size below "supported" minimum in this case.

-  Have tried to combine `FontSize = 19` and usage of `-ms-content-zoom-limit-min:` and `-ms-content-zoom-limit-max:` with custom values below `100%`. For some reasons above properties had effect on each symbol in WebView.

- Have tried to use `-ms-content-zoom-snap-points` https://developer.mozilla.org/en-US/docs/Web/CSS/-ms-content-zoom-snap-points , but haven't seen any effect at all.

In theory, with usage of above `-ms-content-zoom-*` CSS properties should be possible at least to hardcode zooming minimum limit above the "supported" minimum font size to avoid the crash.

**Comment by felixse** [comment]
Managed to stop this with:

```ts
  window.onkeydown = (e) => {
    if (e.ctrlKey && e.key === "Unidentified") {
      e.preventDefault();
    }
  }
```
Don't ask me why it's `Unidentified`, but it works. I think we can do something similar for ctrl + mousewheel. Just wondering if you should offer a custom, non crashing zoom instead?

**Comment by MaxRis** [comment]
> Just wondering if you should offer a custom, non crashing zoom instead?

I think that the possibility to change the font size should be the replacement of zoom. Or if it will be possible somehow to ignore zooming below supported minimum that seems will work great as well.

**Comment by MaxRis** [comment]
@felixse according to https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values "Unidentified" happens when "The user agent wasn't able to map the event's virtual keycode to a  specific key value. This can happen due to hardware or software  constraints, or because of constraints around the platform on which the  user agent is running."

Ignoring of all potential `Unidentified` keys seems is too broad, probably, we can ignore desired keys by their keyCodes `187` and `189`.

Also was able to zoom in/out by CTRL+SHIFT+ numpad's + or -. In this case the key is resolved correctly and equals to "Add" or "Subtract"
