### ISSUE TITLE
SSH profile support

### ISSUE THREAD

**Issue by mjs** [jumptrading/FluentTerminal#3]
FluentTerminal already has the concept of profiles which allow users to configure shells with associated configuration and hotkeys. These can be accessed using the Ctrl-Shift-T and Ctrl-Shift-N default keybindings.

In a similar way to local shell profiles, add support for "SSH profiles" which allows users to define SSH connections to commonly used remote hosts. These should be managed from a new "SSH Profiles"  item at the top level of the Settings UI.

SSH profiles should have the following fields:
- Name
- Username
- Host
- Port
- Identity file path
- Use Mosh option
- Tab color
- Theme
- Use ConPty
- Line ending mode
- Keyboard shortcut

By default, Ctrl-Alt-Y should prompt the user for a SSH profile to use and then start the connection in a new tab. Ctrl-Shift-Alt-Y should prompt the user for a SSH profile to use and then start the connection in a new window. (Ctrl-Shift-Y should be reserved for opening a new ad hoc SSH connection - currently Alt-T).

Although the fields for UI for SSH profiles will be different to local profiles, hopefully much of the backend code for storing SSH profiles can be shared with local profiles.

Given that this feature will be non-trivial and is useful to all FT users, aim to merge this work straight into upstream instead of into the jump master branch first.

**Comment by mjs** [comment]
After starting on this today I think we want a separate configuration UI for SSH profiles but these should be stored alongside the existing local shell profiles. This way the can appear in the same lists when the user hits Ctrl-Shift-T and Ctrl-Shift-N. 

This should be possible by having a BaseProfile model class with ShellProfile and SSHProfile subclasses. Of course, the devil is in the details :)

**Comment by mjs** [comment]
For reference, here's how you can set up a SSH connection with FluentTerminal today: 
![image](https://user-images.githubusercontent.com/14993/55394922-fb3f4e80-559c-11e9-9d33-3e38f6a7ecc9.png)


Please ignore the "SSH Profiles" item in the side bar. That's something I hacked in today (which doesn't work).

**Comment by cjw296** [comment]
How would I set up a mosh one?

**Comment by MaxRis** [comment]
@cjw296  For the moment following workaround should be done:

- After FluentTerminal is installed, copy `mosh.exe` and `mosh-client.exe` from UWP app resources (`C:\Program Files\WindowsApps\53621FSApps.FluentTerminal_0.4.1.0_x64__87x1pks76srcp\MoshExecutables\x64`) to some local folder on your machine.
- Create new profile in Fluent Terminal with path to `mosh.exe` and target machine as input argument
- Open new terminal tab with CTRL+ALT+T


![2019-05-10_16-26-02-mosh-profile-creation](https://user-images.githubusercontent.com/1928902/57531007-2efe5880-7341-11e9-8dc7-3d5443bd5801.gif)

**Comment by peske** [comment]
We have a misunderstanding with @felixse about how this should be implemented. It's not possible to continue until we resolve this, hopefully during todays meeting...

**Comment by peske** [comment]
Just as a reminder: @mjs notes from Slack after his last review:

- Keybindings for SSH profiles don't seem to work
- In Settings, the title for the SSH Profiles section should say "SSH Profiles" - it currently just has "Profiles"
- The SSH profile edit screen should have the "user@host:port" row of fields above identity file field as they're compulsory and more important
- When viewing a SSH profile in Settings the mosh ports shouldn't be shown if the profile isn't using mosh
- When viewing a SSH profile in Settings the fonts for the SSH connection info and Mosh port range are wrong (too big)
- When viewing a SSH profile in Settings the "Ssh Connection Info" label should just be "Connection Info" (the user already knows it's a SSH connection from the surrounding context)
- "Select Ssh Profile" should be "Select SSH Profile" in the New Configurable SSH tab dialog
- A "Configurable SSH Window" keybinding needs to be implemented (default to Ctrl-Shift-Alt-Y). This can be done in a later PR.
- Also in Settings: the "Ssh Port" field label should be "SSH Port"

**Comment by peske** [comment]
I believe that this one is finally closed by https://github.com/felixse/FluentTerminal/pull/390

We'll see after the review.

**Comment by mjs** [comment]
I've run the code in https://github.com/felixse/FluentTerminal/pull/390 and it looks like you've addressed all of my feedback. Thanks very much.

I see a couple of new issues issues which I'll list on the PR itself.

**Comment by peske** [comment]
I believe that all the requirements and all the issues are now solved in https://github.com/jumptrading/FluentTerminal/pull/111, so I'm closing this one.
