### ISSUE TITLE
Automated updates

### ISSUE THREAD

**Issue by mjs** [jumptrading/FluentTerminal#5]
It would be great if Fluent could update itself. It is ok if this is a Jump specific solution (at least initially). Figure out what is possible here. Jump disables the Windows Store so that is a non-starter. https://github.com/google/omaha could be a solution.

**Comment by MaxRis** [comment]
Current application behavior on "in-tray" app startup is to check new version availability at upstream's GitHub Releases page and send Windows notification to visit web page with new release.

**Comment by MaxRis** [comment]
Initial auto update functionality is implemented and merged into your fork. Remaining enhancement work will be done in scope of https://github.com/jumptrading/FluentTerminal/issues/83
