### ISSUE TITLE
[mosh] Arrow keys don't work under vim

### ISSUE THREAD

**Issue by MaxRis** [jumptrading/FluentTerminal#57]
Under mosh run "vi a", type 2 lines, then try to use the up arrow key

**Comment by MaxRis** [comment]
the issue doesn't happen if vi is launched under `tmux` session.
cc @daviesalex

**Comment by mjs** [comment]
Another data point: the problem only happens with vim (not nvim) and only under Mosh.

**Comment by MaxRis** [comment]
Setting `:set term=builtin_ansi` in vi fixes arrows handling for current vi session.

**Comment by MaxRis** [comment]
More background:

- Inside `vi` it's possible to observe escape sequences assigned for various term capabilities taken from terminfo.  Using `mosh` executing of `:set termcap` under `vi` prints `t_kl <Left>      ^[O*D` for left arrow keystroke. Change of `term` value also has impact on expected escape sequences sequences. For example, if `ansi` term is used under `mosh` vi will print termcap as `t_kl <Left>      ^[[D`. In case of `ansi` term Arrows sequences are recognized fine by vi.

- OpenSSH sends the same sequences for arrows keystrokes as Mosh does. The same `^[O*D` escape sequence value for Left Arrow key is expected by `vi` under ssh.exe. Arrows keystrokes under ssh are recognized fine. It means that somewhere exists additional difference in what happens with escape sequence data generated by mosh.

- mosh-server sets TERM for every mosh session on target machine to `xterm` value. OpenSSH uses TERM as `xterm-256color`. It's applicable at least for Ubuntu.

- `htop` launched under `mosh` also can't recognized Up and Down arrows keystrokes to navigate over list of processes. Running `TERM=ansi htop` similar as running `TERM=ansi vi SOME_FILE_NAME` results in correct recognition of arrows keystrokes.

**Comment by MaxRis** [comment]
Next steps:

To determine from where comes the difference with OpenSSH behavior. Since the escape sequences codes generated for key strokes are the same, it might be:

- mosh-client or mosh-server can do something unexpected with escape sequence
- OpenSSH might do some additional data converting before sending it to remote host

**Comment by MaxRis** [comment]
The reason of the issue was wrong mosh client logic to generate not recognizable (which don't match to expected arrows sequences in currently applied vim's termcap) key codes for arrows key strokes ( https://github.com/jumptrading/mosh-windows-wrappers/blob/14007d28baac42fb2518d4173f082339fb154366/client/mosh-client/win32compat/tncon.cc#L248 ).
For the moment mosh client logic modified always to generate arrows key codes under "VTAppMode" with following sequences:
```
#define APP_UP_ARROW                "\x1bOA"
#define APP_DOWN_ARROW              "\x1bOB"
#define APP_RIGHT_ARROW             "\x1bOC"
#define APP_LEFT_ARROW              "\x1bOD"
```
