### ISSUE TITLE
[mosh] Terminal resizing duplicates the output

### ISSUE THREAD

**Issue by MaxRis** [jumptrading/FluentTerminal#58]
Resizing a window also duplicates the output or creates strange artifacts

**Comment by MaxRis** [comment]
The issue seems can be stably reproduced under mosh on latest build. OpenSSH doesn't have such issue on resizing.

**Comment by MaxRis** [comment]
Have tried to start conversation in Slack to collect again issues related to screen resizing under `mosh`.
Duplicated output outside the screen seems doesn't an issue with `mosh`. cc: @mjs

**Comment by mjs** [comment]
FIxing this is likely to be a big time sink and for not much benefit. Let's leave the issue here but mark it as low priority.

**Comment by daviesalex** [comment]
Fairly sure we got this into a place that is as good as we are going to get - closing.
