### ISSUE TITLE
Invalid Form error on pressing Enter for New Remote Shell connection

### ISSUE THREAD

**Issue by MaxRis** [jumptrading/FluentTerminal#63]
First press of Enter generates error message popup as below:

![2019-05-06_20-36-05-invalid-form-error](https://user-images.githubusercontent.com/1928902/57243484-ed1e9b00-703e-11e9-95ee-d88d9f6ea399.png)

**Comment by MaxRis** [comment]
Going to look into this along with Line Endings setting for new remote shell

**Comment by mjs** [comment]
Fixed by #64
