### ISSUE TITLE
Better tab title during ssh/mosh authentication

### ISSUE THREAD

**Issue by mjs** [jumptrading/FluentTerminal#65]
For SSH and Mosh sessions, the tab title doesn't get set until after the connection is established (typically by the remote shell). This means that during password entry or prompts about SSH host keys the tab title is something like `C:\windows\system32\...`. 

A more useful tab title should be set from the beginning. Something like `[ssh] user@host` or `[mosh] user@host`.

**Comment by peske** [comment]
I've just checked, and tab titles look OK to me now.
Mosh:
- Title while authenticating: `mosh`
- Title after authentication: `[mosh] user@host:~`

SSH:
- Title while authenticating: `ssh`
- Title after authentication: `user@host:~`

Is this acceptable?

**Comment by mjs** [comment]
> Is this acceptable?

That looks good although the SSH title is whatever is set by the remote shell. I wonder if there should be a `[ssh]` prefix before whatever the remote shell is setting for the terminal title?

**Comment by peske** [comment]
@mjs, @MaxRis - just found out that ugly tab names (like `C:\windows\system32\...`) are happening with ConPTY. With WinPTY it's as in my previous comment here.

**Comment by peske** [comment]
I've created an upstream PR for this issue: https://github.com/felixse/FluentTerminal/pull/417

Behavior there is unified for both WinPTY and ConPTY, and works like:

Mosh:

    Title while authenticating: `Authenticate`
    Title after authentication: `[mosh] user@host:~`

SSH:

    Title while authenticating: `Authenticate`
    Title after authentication: `[ssh] user@host:~`

@mjs , is this how you wanted tabs to look?

**Comment by mjs** [comment]
@peske Thanks, that looks pretty good. Any reason not to have the `[mosh]` or `[ssh]` prefix during authentication as well?

**Comment by peske** [comment]
@mjs - Just changed as you've requested, and updated the PR. Now there are `[ssh]` and `[mosh]` in front of `"Authenticate"`. The only issue is that currently word _Authenticate_ isn't visible - Felix needs to add it to resources.

**Comment by peske** [comment]
Done. Closing.
