### ISSUE TITLE
Expanding the Advanced section of the SSH dialog can make it unusable

### ISSUE THREAD

**Issue by mjs** [jumptrading/FluentTerminal#67]
Depending on the height of the terminal window, the SSH dialog can become fairly unusable when the Advanced section is expanded.

For example, before:

![image](https://user-images.githubusercontent.com/14993/57264788-10415d00-70c8-11e9-94b6-ce51297eec4b.png)

Then after expanding:

![image](https://user-images.githubusercontent.com/14993/57264810-3404a300-70c8-11e9-9879-48198a50dcf6.png)

Note how it is not even possible to get to all of the newline translation options.

Is there a way to make the controls scrollable when required?

**Comment by peske** [comment]
Solved by https://github.com/jumptrading/FluentTerminal/issues/117
