### ISSUE TITLE
"edit" keybindings doesn't work

### ISSUE THREAD

**Issue by cjw296** [jumptrading/FluentTerminal#77]
Adding some detail here...

The Edit button on the Keybindings setting screen no longer works. We should check if this is specific to the Jump fork or whether it's broken upstream as well.

**Comment by mjs** [comment]
I've confirmed that this happens with upstream master as well. This feature worked until recently so it appears to be a recent regression.

Filed upstream here: https://github.com/felixse/FluentTerminal/issues/366
