### ISSUE TITLE
tmux: resizing windows does not cause tmux to get a resize.

### ISSUE THREAD

**Issue by cjw296** [jumptrading/FluentTerminal#78]
By "go nuts", I mean things get seriously out of whack.

Also, this morning, I get the behaviour shown in the attached image when things settle down:
The tmux window won't grow any bigger (it does in Chrome's ssh client), I just get a border of dots.

**Comment by cjw296** [comment]
Hmm, annoyingly, this actually appears to have trashed the tmux session so that I can't resize it anymore, even when I connect from other clients :-/

**Comment by MaxRis** [comment]
![image(2)](https://user-images.githubusercontent.com/1928902/57516759-04e76f00-731e-11e9-9486-54213b3bc7f7.png)
![image(1)](https://user-images.githubusercontent.com/1928902/57516760-05800580-731e-11e9-9005-a295c5a8025b.png)

**Comment by daviesalex** [comment]
Data point: the Chrome extension mosh client does not do this. Hopefully we can figure out why and have our mosh wrapper (or fluent) do the same thing.

**Comment by mjs** [comment]
The related upstream bug is https://github.com/felixse/FluentTerminal/issues/373

**Comment by mjs** [comment]
https://github.com/felixse/FluentTerminal/issues/373 should largely fix this

**Comment by cjw296** [comment]
@mjs - can we re-open this? Just tried today on the advice of a colleague, and resizing of windows running tmux still doesn't appear to work.

ssh -> remote host -> tmux

resizing the window doesn't result in tmux getting a resize. Only way to fix appears to be to detach and re-attach the tmux session.

**Comment by cjw296** [comment]
-> high priority

**Comment by peske** [comment]
In my latest changes, I've changed something related to resizing, so it may happen that it'll solve the problem. Don't hope too much, but maybe... I'll let you know when these changes are included in the releasse.

**Comment by peske** [comment]
Reopening this one and taking it over.

**Comment by peske** [comment]
I cannot reproduce. Please provide more info. Here's how FT `0.6.1.3` works for me:
https://www.youtube.com/watch?v=-d8gcfbjoZM

**Comment by peske** [comment]
And another demo for `htop` in both WinPTY and ConPTY: https://youtu.be/t2zRAEiuMgg

**Comment by cjw296** [comment]
I can't reproduce over mosh, only over ssh. @peske, is that the same for you?

**Comment by peske** [comment]
No. In both videos I've linked here I've used `ssh`, as you can see. I've also tried with `mosh`. Any combination `ssh`/`mosh` and ConPTY/WinPTY works for me pretty well.

**Comment by mjs** [comment]
@peske Believes that this has been resolved. Please re-open if not.
