### ISSUE TITLE
Application can't be started correctly on ssh/mosh protocols invocation if application was closed

### ISSUE THREAD

**Issue by MaxRis** [jumptrading/FluentTerminal#81]
In case if there is no Fluent Terminal window opened, invoking ssh:// or mosh:// results into hanging of new opened Fluent Terminal window on the start of the opening process.

![2019-05-11_11-40-42-app-hangs-on-start](https://user-images.githubusercontent.com/1928902/57567429-b69ba400-73e1-11e9-8f95-2ad93e10fd27.png)

**Comment by peske** [comment]
In my case this happens only with links without username (i.e. `mosh://192.168.1.1`). Can you confirm that?
I'll try to fix.

**Comment by MaxRis** [comment]
you are right! have the same

**Comment by peske** [comment]
I've fixed this one in https://github.com/jumptrading/FluentTerminal/pull/85.
