### ISSUE TITLE
[mosh] default port is 60000, not 60001

### ISSUE THREAD

**Issue by daviesalex** [jumptrading/FluentTerminal#82]
The default range for mosh is 60001–60999

The chrome plugin starts at 60001

Fluent starts at 60000

Coupled with the UI (which basically swallows the initial error), this is confusing.

Are we passing a 60000 argument somewhere rather than using the first free port from 60001?

**Comment by MaxRis** [comment]
we use for the moment `60000-60050` range by default. It was copy/pasted from mosh-go wrapper.

https://github.com/jumptrading/mosh-windows-wrappers/blob/mosh-client/mosh_cs/Program.cs#L11

As I can see, we shouldn't specify the default range at all to allow mosh-server to use default `60001–60999`

**Comment by peske** [comment]
We are using 60000:60050 from very beginning, but we can change that to any port range if needed.

**Comment by daviesalex** [comment]
Yeah, please just change it to the default (either by passing that, or not passing anything).

I found this because when you add "mosh" to most firewalls, it does not open up 60000 (and the error you get in that case is far from obvious, which we should probably also fix).

**Comment by MaxRis** [comment]
Should be resolved in upstream by https://github.com/felixse/FluentTerminal/pull/371
