### ISSUE TITLE
Ctrl+C doesn't kill process

### ISSUE THREAD

**Issue by ltwojcik** [jumptrading/FluentTerminal#90]
Ctrl-C doesn't seem to be sending a SIGINT to actually kill a running proc. Can reproduce with simple `ping` command

**Comment by lwoj17** [comment]
Even more interesting.. this problem doesn't surface until I've been in the terminal for a while. At first open ctrl-c actually does what you'd expect. After a few SSH and misc commands are run the problem creeps up.

**Comment by peske** [comment]
I couldn't reproduce this one. If it still happens, it would be great if you can record the session, or find another way to show when it happens.

**Comment by MaxRis** [comment]
@lwoj17 does it happen under PowerShell or cmd.exe? I assume that you have started and finished multiple ssh sessions to remote machines before the issue happened to you. It might be also OpenSSH related issue ( Ctrl+C interception is not released correctly by OpenSSH, for example )
